version: '3'
services: 
  web: 
    image: node:14.15
    container_name: okr-tracker
    build: 
      context: .
      dockerfile: shared/config/Dockerfile.dev
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 9000:9000
      - 8888:8888
    environment:
      - CHOKIDAR_USEPOLLING=true